scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'orderprocessing'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['10.0.0.93:9000']